### ISSUE TITLE
Key mapping: can't find the [ ] and copy key

### ISSUE THREAD

**Issue by RikEnde** [0xC0DE6502/electroniq#1]
Tested on a macbook. Wasn't able to try out the inline assembler because I wasn't able to type the [ and ] characters. Are the keyboard mappings configurable?

**Comment by RikEnde** [comment]
Sorry the virtual keyboard solves this

**Comment by 0xC0DE6502** [comment]
Hi Rik, thanks for testing my emulator. The keyboard mapping isn't configurable yet and I haven't been able to test on a macbook. I'm glad the virtual keyboard is of help in this case as well.

**Comment by RikEnde** [comment]
I was writing down some memories about programming on the Electron, and to see if I was remembering the syntax right, I looked for an emulator. It was a surprise to see one that's under active development now, more than 40 years later. I see that you're based in NL, did you buy yours at Kwantum in 1983?

**Comment by 0xC0DE6502** [comment]
I don't remember exactly when/where my parents bought our original Acorn Electron, but I think it was later around 1986 when they were sold cheaply in NL as well. The German model with all the copper shielding inside...
