### ISSUE TITLE
Basic Array syntax doesn't seem to work

### ISSUE THREAD

**Issue by RikEnde** [0xC0DE6502/electroniq#2]
The array syntax doesn't seem to work on a Macbook. Tested in safari and Chrome. The exact same problem also exists in the jsbeeb emulator a thttps://bbcmicro.co.uk/jsbeeb/ 

```
>DIM a% (10)
>a%(0) = 1
Array

10 DIM a% (10)
20 a%(0) = 1
30 PRINT a%(0)

>RUN
Array at line 30
```

**Comment by 0xC0DE6502** [comment]
That's because an array index starts at 1, not at 0. Also, don't put any whitespace before the opening parenthesis.

**Comment by RikEnde** [comment]
Thanks, it looks like the leading space was the problem. Are you sure about the 1-indexed arrays? I've not done this in a long time, but I remember being absolutely shocked by the 1-indexed arrays in fortran

**Comment by 0xC0DE6502** [comment]
You are right. Arrays are 0-indexed, and strings are 1-indexed. Happy coding :)
